server:
  port: 12315

spring:
  application:
    name: eureka-server #应用名称，会在 Eureka 中作为服务的 id 标识（serviceId）

eureka:
  client:
    service-url:  #EurekaServer 的地址，现在是自己的地址，如果是集群，需要写其他 Server 的地址
      defaultZone: http://127.0.0.1:12315/eureka #后缀/eureka为固定写法
    register-with-eureka: false #不注册自己
    fetch-registry: false #不拉取服务
  server:
    eviction-interval-timer-in-ms: 60000 #服务失效剔除时间间隔
    enable-self-preservation: false #关闭自我保护模式（默认为打开）
